import type { Metadata } from "next"
// providers
import { AuthProvider } from "@/shared/context"
// styles
import "@/app/styles"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
